[package]
name = "dice-rs"
version = "0.1.0"
edition = "2024"
links = "dice"
build = "build.rs"
description = "rust bindings for dice"
license = "0bsd"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = ["lto", "dice"]

interpose-memcpy = []
lto = ["dice-dispatch", "dice-box"]

log-fatal = []
log-info  = []
log-debug = []

san-thread = []
san-address = []
san-undefined = []

# Dice modules
dice = []
dice-box = ["dice"]
dice-cxa = ["dice"]
dice-dispatch = ["dice"]
dice-malloc = ["dice"]
dice-memcpy = ["dice"]
dice-mman = ["dice"]
dice-pthread_cond = ["dice"]
dice-pthread_create = ["dice"]
dice-pthread_mutex = ["dice"]
dice-pthread_rwlock = ["dice"]
dice-self = ["dice"]
dice-sem = ["dice"]
dice-tsan = ["dice"]

[dependencies]
dice-derive = { version = "0.1", path = "../dice-derive" }
libc = "0.2.177"
ctor = "0.6.0"
log = "0.4.28"

[build-dependencies]
cmake = "0.1.54"
cc = "1.2.41"
walkdir = "2.5.0"
ar = "0.9.0"
