[package]
name = "dice-rs"
version = "0.1.0"
edition = "2024"
links = "dice"
build = "build.rs"
description = "rust bindings for dice"
license = "0bsd"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = ["dice"]

interpose-memcpy = []
lto = [] # ["dice-box"] TODO: add again after #14

log-fatal = []
log-info  = []
log-debug = []

san-thread = []
san-address = []
san-undefined = []

manual-link = []

# Dice modules
dice = []
dice-box = ["dice"]
dice-cxa = ["dice"]
dice-epoll = ["dice"]
dice-eventfd = ["dice"]
dice-fcntl = ["dice"]
dice-malloc = ["dice"]
dice-memcpy = ["dice"]
dice-mman = ["dice"]
dice-pthread_cond = ["dice"]
dice-pthread_create = ["dice"]
dice-pthread_mutex = ["dice"]
dice-pthread_rwlock = ["dice"]
dice-self = ["dice"]
dice-sem = ["dice"]
dice-tsan = ["dice"]
dice-poll = ["dice"]
dice-random = ["dice"]
dice-socket = ["dice"]
dice-time = ["dice"]
dice-uio = ["dice"]
dice-unistd = ["dice"]

[dependencies]
dice-derive = { version = "0.1", path = "../dice-derive" }
libc = "0.2.177"
ctor = "0.6.0"
log = "0.4.28"

[build-dependencies]
cmake = "0.1.54"
cc = { version = "1.2.48", features = ["parallel"] }
walkdir = "2.5.0"
ar = "0.9.0"
bindgen = "0.72.1"
regex = "1"