[package]
name = "dice-rs"
version = "0.1.0"
edition = "2024"
links = "dice"
build = "build.rs"
description = "dice-rs"
license = "0bsd"

[features]
default = ["lto"]

interpose-memcpy = []
lto = []

log-fatal = []
log-info  = []
log-debug = []

san-thread = []
san-address = []
san-undefined = []

[dependencies]
dice-derive = { version = "0.1", path = "../dice-derive" }
libc = "0.2.177"
ctor = "0.6.0"
log = "0.4.28"

[build-dependencies]
cmake = "0.1.54"
bindgen = "0.72.1"
heck = "0.5.0" 
cc = "1.2.41"