[package]
name = "recorder"
version = "0.1.0"
edition = "2024"
license = "0bsd"

[lib]
name = "recorder"
crate-type = ["rlib", "staticlib"]

[dependencies]
dice-rs = { version = "0.1", path = "../../dice-rs", features = ["dice-pthread_create", "dice-self", "dice-tsan", "dice-malloc"] }
ctor = "0.6.0"
log = "0.4.28"
