name: Test dice-rs

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
  repository_dispatch:
    types: [ test-dice ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout Dice
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: actions/checkout@v4
        with:
          repository: open-s4c/dice
          ref: ${{ github.event.client_payload.commit }}
          path: dice
          submodules: recursive
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose
      - name: Generate a token
        if: ${{ always() && github.event_name == 'repository_dispatch' }}
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          repositories: dice
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Update Upstream Test Check
        if: ${{ always() && github.event_name == 'repository_dispatch' }}
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          repo: open-s4c/dice
          sha: ${{ github.event.client_payload.commit }}
          token: ${{ steps.generate-token.outputs.token }}
          check_id: ${{ github.event.client_payload.check_id }}
          conclusion: ${{ job.status }}
          status: completed
          output: |
            {"title":"dice-rs tests for Dice commit ${{ github.event.client_payload.commit }}","summary":"See workflow run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"}
