name: Test dice-rs

on:
  push:
  pull_request:
  repository_dispatch:
    types: [ test-dice ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout Dice
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: actions/checkout@v4
        with:
          repository: open-s4c/dice
          ref: ${{ github.event.client_payload.sha }}
          path: dice
          submodules: recursive
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose
      - name: Create Downstream Test Check
        if: ${{ always() }}
        uses: LouisBrunner/checks-action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: test
          conclusion: ${{ job.status }}
          status: completed
          output: |
            {"summary":"See workflow run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"}
