name: Test dice-rs

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
  repository_dispatch:
    types: [ test-dice ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Checkout Dice
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: actions/checkout@v6
        with:
          repository: open-s4c/dice
          ref: ${{ github.event.client_payload.commit }}
          path: dice
          submodules: recursive
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo test
      - name: Publish results to Dice
        if: ${{ always() && github.event_name == 'repository_dispatch' }}
        uses: ./dice
        with:
          status: ${{ job.status }}
          title: 'dice-rs tests for Dice commit ${{ github.event.client_payload.commit }}'
          summary: 'See workflow run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
          commit: ${{ github.event.client_payload.commit }}
          check_id: ${{ github.event.client_payload.check_id }}
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
